import type { FlowDefinition } from '@/types'

export const FLOW_DEFINITIONS: Record<string, FlowDefinition> = {
  understand: {
    id: 'understand',
    title: 'Understand What Happened',
    tagline: 'For confusing moments, mixed signals, conflict, or emotional uncertainty.',
    estimatedMinutes: 8,
    steps: [
      {
        id: 'what_happened',
        type: 'text_input',
        question: 'What happened?',
        hint: 'Describe the situation in your own words. You don\'t need to have it figured out.',
        placeholder: 'E.g. "We had an argument after dinner and they left without saying anything."',
        required: true,
        triggersAI: false,
      },
      {
        id: 'who_involved',
        type: 'single_select',
        question: 'Who is involved?',
        hint: 'What is this person\'s relationship to you?',
        options: [
          'Romantic partner',
          'Ex-partner',
          'Friend',
          'Family member',
          'Parent',
          'Sibling',
          'Colleague',
          'Manager / boss',
          'Other',
        ],
        required: true,
        triggersAI: false,
      },
      {
        id: 'they_said_did',
        type: 'text_input',
        question: 'What did the other person say or do?',
        hint: 'Try to stick to what actually happened — their words or actions, not your interpretation.',
        placeholder: 'E.g. "They said \'you always do this\' and walked out of the room."',
        required: true,
        triggersAI: false,
      },
      {
        id: 'i_said_did',
        type: 'text_input',
        question: 'What did you say or do?',
        hint: 'Be honest with yourself. There\'s no judgment here.',
        placeholder: 'E.g. "I raised my voice and said something I didn\'t mean."',
        required: true,
        triggersAI: false,
      },
      {
        id: 'feelings',
        type: 'emotion_picker',
        question: 'How did it make you feel?',
        hint: 'Select everything that applies, even if some feel contradictory.',
        options: [
          'Hurt', 'Angry', 'Sad', 'Confused', 'Scared',
          'Disappointed', 'Lonely', 'Frustrated', 'Numb', 'Betrayed',
          'Relieved', 'Hopeful', 'Guilty', 'Ashamed', 'Anxious',
        ],
        required: true,
        triggersAI: false,
      },
      {
        id: 'fear_meaning',
        type: 'text_input',
        question: 'What are you afraid this means?',
        hint: 'E.g. "That they don\'t respect me," "That I\'m too much," or "That this is the end."',
        placeholder: 'What\'s the story you\'re telling yourself about it?',
        required: true,
        triggersAI: false,
      },
      {
        id: 'happened_before',
        type: 'single_select',
        question: 'Has this happened before?',
        options: [
          'No, this is new',
          'Once or twice',
          'Yes, a few times',
          'Yes, it\'s a recurring pattern',
        ],
        required: true,
        triggersAI: false,
      },
      {
        id: 'healthy_outcome',
        type: 'text_input',
        question: 'What outcome would feel healthy or fair to you?',
        hint: 'This isn\'t about what you think is realistic — just what would feel right.',
        placeholder: 'E.g. "I want them to acknowledge what they said. I want to feel heard."',
        required: true,
        triggersAI: false,
      },
      {
        id: 'summary',
        type: 'summary',
        question: 'Your reflection:',
        aiPromptKey: 'understand_summary',
        required: false,
        triggersAI: true,
      },
    ],
  },

  prepare: {
    id: 'prepare',
    title: 'Prepare a Difficult Conversation',
    tagline: 'For sensitive messages, boundaries, apologies, feedback, or emotional honesty.',
    estimatedMinutes: 10,
    steps: [
      {
        id: 'conversation_with',
        type: 'single_select',
        question: 'Who is the conversation with?',
        options: [
          'Romantic partner',
          'Ex-partner',
          'Friend',
          'Family member',
          'Parent',
          'Sibling',
          'Colleague',
          'Manager / boss',
          'Other',
        ],
        required: true,
        triggersAI: false,
      },
      {
        id: 'situation',
        type: 'text_input',
        question: 'What is the situation?',
        hint: 'Give context. What\'s been going on, and why does this conversation feel necessary?',
        placeholder: 'E.g. "My partner dismisses my feelings when I try to bring up something that bothers me."',
        required: true,
        triggersAI: false,
      },
      {
        id: 'want_them_to_understand',
        type: 'text_input',
        question: 'What do you want them to understand?',
        hint: 'What\'s the core thing you need them to hear — not the argument, but the feeling underneath it?',
        placeholder: 'E.g. "I need them to understand that I feel invisible when my concerns are brushed off."',
        required: true,
        triggersAI: false,
      },
      {
        id: 'need_ask_for',
        type: 'text_input',
        question: 'What do you need or want to ask for?',
        hint: 'Be as specific as you can. A behavior, a boundary, an acknowledgment, or something else?',
        placeholder: 'E.g. "I want to ask them to pause and listen before responding."',
        required: true,
        triggersAI: false,
      },
      {
        id: 'tone',
        type: 'single_select',
        question: 'What tone do you want to bring?',
        hint: 'There\'s no wrong answer — just what feels right for this moment.',
        options: [
          'Calm and clear',
          'Warm and open',
          'Direct but kind',
          'Firm and assertive',
          'Curious — I want to understand them too',
        ],
        required: true,
        triggersAI: false,
      },
      {
        id: 'want_to_avoid',
        type: 'multi_select',
        question: 'What do you want to avoid?',
        hint: 'Select anything that feels relevant.',
        options: [
          'Making them defensive',
          'Starting an argument',
          'Saying something I\'ll regret',
          'Being dismissed or shut down',
          'Losing the relationship',
          'Escalation or conflict',
          'Crying or losing composure',
        ],
        required: false,
        triggersAI: false,
      },
      {
        id: 'conversation_safety',
        type: 'single_select',
        question: 'Is there any risk that this conversation could become unsafe?',
        hint: 'This could mean emotionally unsafe, or physically unsafe. Your honesty here matters.',
        options: [
          'No, I feel safe with this person',
          'Possibly — they can get reactive or dismissive',
          'Yes, I have safety concerns',
        ],
        required: true,
        triggersAI: false,
        safetyTriggerValues: ['Yes, I have safety concerns'],
      },
      {
        id: 'summary',
        type: 'summary',
        question: 'Your conversation guide:',
        aiPromptKey: 'prepare_summary',
        required: false,
        triggersAI: true,
      },
    ],
  },

  decide: {
    id: 'decide',
    title: 'Decide My Next Step',
    tagline: 'For deciding whether to stay engaged, step back, ask for change, or set a boundary.',
    estimatedMinutes: 7,
    steps: [
      {
        id: 'relationship',
        type: 'text_input',
        question: 'What relationship are you thinking about?',
        hint: 'Describe who this person is to you and how long you\'ve known each other.',
        placeholder: 'E.g. "My partner of two years" or "A close friend I\'ve known since college."',
        required: true,
        triggersAI: false,
      },
      {
        id: 'questioning',
        type: 'text_input',
        question: 'What is making you question the situation?',
        hint: 'What\'s been happening that brought you here today?',
        placeholder: 'E.g. "I keep feeling drained after we spend time together and I\'m not sure why."',
        required: true,
        triggersAI: false,
      },
      {
        id: 'good_valuable',
        type: 'text_input',
        question: 'What has been good or valuable in this relationship?',
        hint: 'Think about what you\'d miss, what works, or what you genuinely appreciate.',
        placeholder: 'E.g. "They\'re the first person I call when something good happens."',
        required: true,
        triggersAI: false,
      },
      {
        id: 'painful_confusing',
        type: 'text_input',
        question: 'What has been painful, confusing, or unhealthy?',
        hint: 'Be honest. You don\'t have to minimize it or explain it away.',
        placeholder: 'E.g. "They make plans with me and cancel last minute. I end up feeling like an option."',
        required: true,
        triggersAI: false,
      },
      {
        id: 'communicated_before',
        type: 'single_select',
        question: 'Have you communicated your needs or boundaries before?',
        options: [
          'Yes, clearly and directly',
          'I\'ve hinted at it but not said it outright',
          'I\'ve tried but it didn\'t land the way I meant',
          'No, not yet',
        ],
        required: true,
        triggersAI: false,
      },
      {
        id: 'their_response',
        type: 'text_input',
        question: 'How did the other person respond?',
        hint: 'If you haven\'t communicated yet, describe how you imagine they might respond.',
        placeholder: 'E.g. "They apologized in the moment but the same pattern repeated."',
        required: true,
        triggersAI: false,
      },
      {
        id: 'what_would_change',
        type: 'text_input',
        question: 'What would need to change for this to feel healthier?',
        hint: 'Think about behavior, patterns, communication — not a perfect version of the person.',
        placeholder: 'E.g. "They\'d need to follow through on what they say, even in small things."',
        required: true,
        triggersAI: false,
      },
      {
        id: 'safety_concerns',
        type: 'single_select',
        question: 'Are there any safety concerns?',
        hint: 'This includes emotional, psychological, or physical safety.',
        options: [
          'No, I feel safe',
          'I\'m not sure — something feels off',
          'Yes, I have concerns about my safety',
        ],
        required: true,
        triggersAI: false,
        safetyTriggerValues: ['Yes, I have concerns about my safety'],
      },
      {
        id: 'summary',
        type: 'summary',
        question: 'Your clarity summary:',
        aiPromptKey: 'decide_summary',
        required: false,
        triggersAI: true,
      },
    ],
  },
}

export function getFlow(flowId: string): FlowDefinition | null {
  return FLOW_DEFINITIONS[flowId] ?? null
}
